name: Python CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Run Flake8
      run: poetry run flake8

    - name: Run Safety Check
      run: poetry run safety check

    - name: Run Black
      run: poetry run black --check .

    - name: Run Pytest
      run: poetry run pytest
